on:
  workflow_dispatch:
    inputs:
      version_project:
        description: 'Project version'
        required: true
  
name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: v.${{ inputs.version_project }}
          release_name: Release v.${{ inputs.version_project }}
          body: |
            Test
          draft: false
          prerelease: false